Fix issue for toggle sp
When VNX driver is configured on [default] section,
configuration.conig_group is None. This can cause following error if toggle
happens:
TypeError: cannot concatenate 'str' and 'NoneType' objects

This patch fixes this by providing a default name for above scenario.